### PR TITLE
Add support for multiple GitHub endpoints.

### PR DESCRIPTION
**Pull request by monochromegane**
This adds support for multiple GitHub endpoints.

see: https://github.com/janinko/ghprb/issues/122

Thanks for the great plugin.

### CODE REVIEW

**Comment by DavidTanner** [comment]
I am working on a new branch.

**Comment by Drdoteam** [comment]
Hi, I want to use this function in my jenkins.
When would you release it ?

**Comment by Drdoteam** [comment]
I built "multiple-github-endpoints" branch and run it by "hpi:run".
But, I can't see its UI in Jenkins and Build Job configure pages.
Is there any problems ?
I hard to find why its UI is not shown.

**Comment by Drdoteam** [comment]
Please check https://github.com/janinko/ghprb/pull/251

**Comment by sgykfjsm** [comment]
Hi.

Do you have a plan to merge multiple-github-endpoints branch into master?

**Comment by DavidTanner** [comment]
https://github.com/DavidTanner/ghprb-plugin/tree/github-auth will handle the multiple endpoints, uses credentials, and allows the webhooks to work the same.  I still have some work to do on it, but please feel free to review it.

**Pull request closed without merging**
