### PR TITLE
Support for folders

### PR DESCRIPTION
**Pull request by tamasflamich**
Presumably solves [this issue](https://github.com/janinko/ghprb/issues/208).

### CODE REVIEW

**Comment by CsabaSzabo** [comment]
+1
simple solution, useful feautre

**Comment by s0undt3ch** [comment]
:+1:

**Comment by DavidTanner** [comment]
This is definitely a worth merging in, the only problem I see is that it is going to break builds.  Is that okay, or is there a way to migrate?

**Comment by s0undt3ch** [comment]
Why is it going to break builds?

**Comment by tamasflamich** [comment]
Root jobs will work exactly like before (full name = name). Child jobs were never supported, their behaviour was literally undefined. I don't see why this would be a breaking change.

**Comment by DavidTanner** [comment]
Works for me.

**Pull request merged**
