### PR TITLE
Skip builds for unmerged pullrequests

### PR DESCRIPTION
**Pull request by sradi**
Hi,

in our company, we would like to make sure, that builds for a new pull request are only triggered, if that PR is in a mergeable state. I thought, this feature might be interesting for others as well.
Can you imagine, to introduce this feature into your codebase?

Additionally ghprb could add a comment to the pull request, to inform the user about the fact, that Jenkins won't execute a build, until it is in a mergeable state. Else, a user might get confused, if he enters "test this please" and nothing happens.

### CODE REVIEW

**Comment by walliski** [comment]
:+1: I like the idea, it's confusing that Jenkins says the PR is successful, when you can't even merge it.

**Comment by pankajgrovertt** [comment]
Can one of the admins verify this patch?

**Comment by DavidTanner** [comment]
This PR needs to be cleaned up and merged with master.  I am trying to avoid adding new settings to setup page, unless they are set up as extensions that can be added to the setup.   If you want to add an extension instead please submit the pr to jenkinsci/ghprb-plugin

**Comment by sradi** [comment]
@DavidTanner In PR #221 you mentioned, that you're planning a v2.0 of ghprb with extensions. I would like to implement an extension, which skips a build, when a pullrequest is not mergeable.

Is there any example code, that shows how to implement extensions for ghprb, and is there a schedule for v2.0?

**Comment by DavidTanner** [comment]
I realized that extensions could be added and keep all backwards compatibility so I have no plans for a v2.  Just check the current extensions to see how to implement, like simplestatus

**Pull request closed without merging**
