### PR TITLE
GhprbTrigger: add ghprbCommentBody value

### LINKED ISSUE #312: Access GitHub pull request description body
Is it possible to get the actual body (markdown) of the pull request description?

I want to be able to add custom phrases to skip certain stuff during build.

### PR DESCRIPTION
**Pull request by williamboman**
Closes #312.

### CODE REVIEW

**Comment by sharkySharks** [comment]
I am having a hard time finding which version this is part of. I am using version `1.24.4` currently and do not see this environment variable available. Anyone know which version this was included in?

**Comment by williamboman** [comment]
> Anyone know which version this was included in?

**Comment by williamboman** [comment]
First release this was in seems to have been `1.27`

**Comment by sharkySharks** [comment]
Thanks for the quick response @williamboman ! I'll see about bumping up to `1.27`

**Pull request closed without merging**
