### PR TITLE
Add support for github labels ignore list

### PR DESCRIPTION
**Pull request by udisch**
Adds a configuration which allows to configure github labels that, if present on the pull request, will skip the build. This is useful when working on a pull request that is still in progress, and you don't want commits to trigger a build.

### CODE REVIEW

**Comment by udisch** [comment]
Will re-create in jenkins-ci

**Comment by gdgib-bina** [comment]
@udisch did you ever reopen this?  I couldn't find the PR in https://github.com/jenkinsci/ghprb-plugin and I'd love to.

**Comment by udisch** [comment]
@gdgib-bina Yes, it was added, rolled back and eventually redone by someone else. It's already merged.
https://github.com/jenkinsci/ghprb-plugin/pull/449

**Comment by gdgib-bina** [comment]
Thank you @udisch !

**Pull request closed without merging**
